// if (req.header === 'production') {
// 	module.exports = require('./production.keys');
// } else {
// 	module.exports = require('./development.keys');
// }
module.exports = {
  SMS: {
    WELCOME_MESSAGE: '{!{name}!} have salary of {!{amount}!} rupees per day',
    OTP_MESSAGE: 'Dear User, This is your otp {!{otp}!} to verify your account.'
  },
  MESSAGE: {
    FETCH_SUCCESS: 'Data successfully fetched',
    GENERAL_CATCH_MESSAGE: 'Something went wrong. Please try again later',
    TWILIO_SMS_SEND_SUCCESS: 'SMS sent successfully',
    EMAIL_ALREADY_EXISTS: 'Email already exists',
    MOBILE_ALREADY_EXISTS: 'Mobile number already exists',
    USER_NAME_ALREADY_EXISTS: 'User name already exists',
    USER_MOBILE_NOT_EXISTS: 'User with this mobile number not found',
    AGE_VALIDATION: 'Age should be 18 or older.',
    REFER_CODE_NOT_AVAILABLE: 'Referral code is not available.',
    USER_TYPE_REQUIRED: 'User type is required',
    NEW_USER_CREATED: 'New user created successfully',
    OTP_SENT: 'OTP has been sent succesfully',
    USER_EMAIL_NOT_FOUND: 'User with this email not found.',
    USER_ACTIVATION_ERROR: 'Please activate your account.',
    USER_ACTIVATION: 'User activated successfully',
    USER_DEACTIVATE: 'User deactivated successfully',
    USER_DETAILS_NOT_AVAILABLE: 'User details not available',
    USER_DETAILS_NOT_FOUND: 'User not found, Please sign up.',
    USER_PANCARD_EXIST: 'User with this pancard number is already exist. Please report if it\'s not you.',
    PANCARD_DETAIL_UPDATED: 'Pancard details updated successfully.',
    SUB_ADMIN_ACTIVATION: 'Sub Admin activated successfully',
    SUB_ADMIN_DEACTIVATE: 'Sub Admin deactivated successfully',
    SUB_ADMIN_DETAILS_NOT_AVAILABLE: 'Sub admin details not available',
    UNAUTHRIZED_LOGIN: 'Unauthorized, please login',
    UNAUTHRIZED_ACCESS: 'Unauthorized access',
    ACCOUNTANT_DETAILS_NOT_AVAILABLE: 'Accountant details not available',
    ACCOUNTANT_ACTIVATION: 'Accountant activated successfully',
    ACCOUNTANT_DEACTIVATE: 'Accountant deactivated successfully',
    INVALID_PASSWORD: 'Invalid password',
    PASSWORD_MIN_LENGTH: 'Password must be 6 charachter long',
    PASSWORD_UPDATE_SUCCESS: 'Password updated successfully',
    PROFILE_FETCH_SUCCESS: 'Profile retrieved successfully',
    USER_DATA_RETRIEVED_SUCCESS: 'User data retrieved successfully',
    PROFILE_UPDATE_SUCCESS: 'Profile updated successfully',
    LOGOUT_FAILED: 'User logout failed',
    LOGOUT_SUCCESS: 'User logout successfully',
    MULTIPLE_DEVICE_LOGIN_NOT_ALLOWED:
      'Multiple device login are not allowed, please logout from device first',
    FORGOTPASSWORD_EMAIL_SUCCESS: 'Email has been sent successfully.',
    FORGOTPASSWORD_EMAIL_FAIL: 'Error while sending email.',
    FORGOTPASSWORD_OTP_SUCCESS: 'OTP has been sent successfully.',
    FORGOTPASSWORD_OTP_FAIL: 'Error while sending OTP.',
    TITLE_ALREADY_EXISTS: 'Title already exists.',
    EMAIL_FORMAT_CREATED_SUCCESS: 'Email format created successfully.',
    EMAIL_FORMAT_UPDATED_SUCCESS: 'Email format updated successfully.',
    NO_EMAIL_FORMAT_EXISTS: 'No email format exists.',
    EMAIL_TEMPLATE_RETRIEVE: 'Email Template retrieve successfully.',
    EMAIL_TEMPLATE_DELETED: 'Email Template deleted successfully.',
    SMS_TEMPLATE_CREATED_SUCCESS: 'SMS Template created successfully.',
    SMS_TEMPLATE_UPDATED_SUCCESS: 'SMS Template updated successfully.',
    NO_SMS_TEMPLATE_EXISTS: 'No SMS template exists.',
    NO_SMS_FORMAT_EXISTS: 'No SMS format exists.',
    SMS_TEMPLATE_RETRIEVE: 'SMS Template retrieve successfully.',
    SMS_TEMPLATE_DELETED: 'SMS Template deleted successfully.',
    VERSION_ALREADY_EXISTS: 'Version already exists.',
    VERSION_NUMBER_LOWER: "Version Number can't be lower than the exists one.",
    VERSION_NUMBER_CREATED_SUCCESS: 'Version Number created successfully.',
    NO_VERSION_DETAILS_EXISTS: 'No version details available.',
    VERSION_DETAIL_RETRIEVE: 'Version details retrieve successfully.',
    OPTIONAL_UPDATE: 'This is an optional update.',
    FORCE_UPDATE: 'This is a force update.',
    NO_UPDATE: 'No update require.',
    SELF_FOLLOW: "You can't follow your self.",
    ALREADY_FOLLOWING: 'You are already following this user.',
    FOLLOW_SUCCESS: 'You are now following this user.',
    UNFOLLOW_SUCCESS: 'You have unfollowed this user.',
    BADGE_CREATE_SUCCESS: 'Badge created successfully.',
    BADGE_UPDATE_SUCCESS: 'Badge updated successfully.',
    BADGE_DELETE_SUCCESS: 'Badge deleted successfully.',
    BADGE_ALREADY_EXIST: 'Badge already exist.',
    BADGE_NOT_EXIST: 'Badge not found.',
    BADGE_DETEAIL_SUCCESS: 'Badge deteails fatched successfully.',
    CMS_CREATE_SUCCESS: 'CMS created successfully.',
    CMS_RETRIEVE_SUCCESS: 'CMS list retrieved successfully.',
    CMS_UPDATE_SUCCESS: 'CMS updated successfully.',
    CMS_DELETE_SUCCESS: 'CMS deleted successfully.',
    CMS_NOT_FOUND: 'CMS details not found.',
    CMS_TITLE_EXIST: 'CMS title already exist.',
    CMS_SLUG_EXIST: 'CMS slug already exist.',
    TITLE_REQUIRED: 'Please enter the title.',
    MAX_PARTICIPANTS_REQUIRED: 'Please enter number of maximum participants.',
    TRIVIA_EXSITS: 'Trivia already exists with this name.',
    TRIVIA_CREATE_SUCCESS: 'Trivia successfully created.',
    TRIVIA_CREATE_TIME_ERROR:
      'You have to launch trivia at least 1 day ago or maximum 10 days ago.',
    TRIVIA_ENROLL_TIME_ERROR:
      "Trivia enrollment time should be higher than it's start time.",
    TRIVIA_ENROLL_START_TIME_ERROR:
      'Trivia enrollment time should be start 1 day ago or maximum 10 days ago.',
    TRIVIA_END_TIME_ERROR:
      "Trivia start time should be higher than it's end time.",
    TRIVIA_NOT_FOUND: 'Trivia details not found.',
    TRIVIA_FOUND: 'Trivia details retrieved successfully.',
    TRIVIA_EDIT_TIME_DONE: "Sorry you can't edit trivia.",
    TRIVIA_UPDATE: 'Trivia updated successfully.',
    TRIVIA_CLOSE:
      "Sorry you can't participate in this trivia as it's no longer available.",
    TRIVIA_PARTICIPATE_FULL:
      "Sorry you can't participate in this trivia as it has reached it's participants limit.",
    TRIVIA_LIST_ALREADY_EXIST: 'Trivia winner list already exist.',
    TRIVIA_LIST_GENERATE_SUCCESS: 'Trivia winner list generated successfully.',
    LINK_EXPIRED: 'Your link has been expired.',
    PASSWORD_RESET_SUCCESS: 'Your password has been reset successfully',
    ORDER_CREATED : 'Order created successfully.',
    BENEFICIARY_ADDED_SUCCESSFULLY: 'Beneficiary added successfully.',
    BENEFICIARY_ALREADY_ADDED: 'Beneficiary already added.',
    BENEFICIARY_REMOVED_SUCCESSFULLY: 'Beneficiary removed successfully.',
    GLOBAL_GENERAL_SETTINGS_CREATED_SUCCESS:
      'Global general settings created successfully.',
    GLOBAL_GENERAL_SETTINGS_NOT_FOUND: 'Global general settings not found.',
    GLOBAL_GENERAL_SETTINGS_RETRIEVE:
      'Global general settings retrieve succesfully.',
    GLOBAL_GENERAL_SETTINGS_UPDATED_SUCCESS:
      'Global general settings updated successfully.',
    GLOBAL_TEAM_SETTINGS_CREATED_SUCCESS:
      'Global team settings created successfully.',
    GLOBAL_TEAM_SETTINGS_NOT_FOUND: 'Global team settings not found.',
    GLOBAL_TEAM_SETTINGS_RETRIEVE: 'Global team settings retrieve succesfully.',
    GLOBAL_TEAM_SETTINGS_UPDATED_SUCCESS:
      'Global team settings updated successfully.',
    GLOBAL_BOOSTER_SETTINGS_CREATED_SUCCESS:
      'Global booster settings created successfully.',
    GLOBAL_BOOSTER_SETTINGS_NOT_FOUND: 'Global booster settings not found.',
    GLOBAL_BOOSTER_SETTINGS_RETRIEVE:
      'Global booster settings retrieve succesfully.',
    GLOBAL_BOOSTER_SETTINGS_UPDATED_SUCCESS:
      'Global booster settings updated successfully.',
    GLOBAL_POINT_SETTINGS_CREATED_SUCCESS:
      'Global point settings created successfully.',
    GLOBAL_POINT_SETTINGS_NOT_FOUND: 'Global point settings not found.',
    GLOBAL_POINT_SETTINGS_RETRIEVE:
      'Global point settings retrieve succesfully.',
    GLOBAL_POINT_SETTINGS_UPDATED_SUCCESS:
      'Global point settings updated successfully.',
    REFERRED_DATA_NOT_AVAILABLE: 'Referred data not availbale.',
    REFERRED_DATA_RETRIEVE_SUCCESS: 'Referred data retrieve succesfully.',
    ALREADY_REGISTERED_USER: 'You already have registered.',
    USER_REGISTERED_SUCCESS: 'You have registered successfully.',
    ANSWER_SUBMITTED_SUCCESS: 'You have submitted your answers successfully.',
    WINNER_LIST: 'Winner list retrieved successfully.',
    NOT_ENOUGH_BALANCE:
      'You seems to have a low balance, Please recharge to participate.',
    NEW_BOT_CREATED: 'New bot created successfully.',
    FOUND_DUPLICATE_ENTRY: 'Duplicate entry retrieve successfully.',
    KIT_IMAGE_CREATED_SUCCESS: 'Kit created successfully.',
    KIT_IMAGES_RETRIVE: 'Kit details fatch successfully.',
    KIT_IMAGE_NOT_FOUND: 'Kit image not found.',
    KIT_IMAGES_DELETE_SUCCESS: 'Kit image deleted successfully.',
    KIT_LOGO_CREATED_SUCCESS: 'Kit created successfully.',
    KIT_LOGO_RETRIVE: 'Kit details fatch successfully.',
    KIT_LOGO_NOT_FOUND: 'Kit logo not found.',
    KIT_LOGO_DELETE_SUCCESS: 'Kit logo deleted successfully.',
    FAQ_CREATED_SUCCESS: 'FAQ created successfully.',
    FAQ_EDITED_SUCCESS: 'FAQ edited successfully.',
    FAQ_DELETED_SUCCESS: 'FAQ deleted successfully.',
    FAQ_GET_SUCCESS: 'FAQ retrieved successfully.',
    FAQ_GET_ALL_SUCCESS: 'FAQs retrieved successfully.',
    USER_KIT_CREATED_SUCCESS: 'User kit created successfully.',
    USER_KIT_RETRIVE: 'User kit fatched successfully.',
    PANCARD_DETAIL_FAIL : 'Pancard details does not match'
  }
};
